import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import {MicrophoneIcon, MagnifyingGlassIcon} from "@heroicons/react/20/solid"
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */} 

      <Header />

      {/* Body */} 

      <form className='flex flex-col items-center mt-36'>
        <Image 
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Google_2015_logo.svg/1200px-Google_2015_logo.svg.png" 
          width="300"
          height="100"
        />
        <div className="flex mt-6 border border-gray-200 px-5 py-3 w-full max-w-[90%] mx-auto hover:shadow-lg focus-within:shadow-lg rounded-full items-center sm:max-w-xl lg:max-w-2xl">
          <MagnifyingGlassIcon className="h-5 text-gray-500 mr-3"/>
          <input type="text" placeholder="Search google or type any url" className="flex-grow focus:outline-none object-cover"/>
          <MicrophoneIcon className="h-5 text-gray-500 ml-3" />
        </div>
        {/* Buttons */}
        <div className='mt-6 flex gap-2 justify-center'>
          <button className="btn">Google Search</button>
          <button className="btn">I'm Feeling Lucky</button>
        </div>
      </form>

      {/* Footer */} 
      <Footer />
    </div>
  )
}
